#.SUFFIXES: .o .c

CC = gcc
RM = rm -rf
WOPTION = -W -Wall -Wconversion -Wshadow -Wcast-qual
# -W : signed & unsigned comparison / condition body / condition context
# -Wall : specification of return value
# -Wconversion : type conversion
# -Wshadow : scope of variable
# -Wcast-qual : wrong usage of type constraint (const variable)
# -Wtraditional : check errors strictly by ANSI/ISO standard (used to write code at the other computer platform)

SRC_HOME = ../../src
CFLAGS = -I../../include
#CFLAGS = -I${HOME}/src_test/ttlib/include

TARGET = run
OBJS = $(SRCS:%.c=%.o)
SRCS = strlib_test.c strlib.c ${SRC_HOME}/ttlib.c

